server.servlet.context-path: /api

debug: true
logging:
  level.root: DEBUG
  pattern.console: "[%-5level] %logger.%M - %msg%n"
  # Stream the stdout to CloudWatch log via ECS
  # file: log/tp-sample-service-production.log

#spring:
#  datasource:
#    url: jdbc:mysql://aurora1-us-east-1c.cihcillp9cmv.us-east-1.rds.amazonaws.com:3306/tp_sample_production?useSSL=false
#    username: coder
#    password: tc3secureds
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      idle-timeout: 360000

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: healthcheck

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048


#auth0:
#  issuer: https://tc3-dev.auth0.com/
#  audience: dev1.comunity.tc3.com

cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,HEAD

deploy:
  aws:
    region: us-west-2
    ecs:
      cluster:
        name: secureds-api-cluster
        service:
          name: tp-dummy-service
