server.servlet.context-path: /api

debug: true
logging:
  level.root: DEBUG

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/tp_sample_development?useSSL=false
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      idle-timeout: 60000

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: healthcheck

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST
