AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 128

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Max: 60

